added model User, UserDao and UserService
Ilya-brinchuk/spring-project pull request #1
Opened 2021-02-08 20:01 UTC by Ilya-brinchuk

2021-02-08 20:07 UTC, RuslanIbIsh approved these changes

2021-02-09 07:50 UTC, Sofasmile requested changes

2021-02-09 07:50 UTC, Sofasmile commented on src/main/java/com/spring/dao/impl/UserDaoImpl.java
> +    private SessionFactory sessionFactory;
https://mate-academy.github.io/jv-program-fulltime/04_spring/checklist/hw_01.html
> What is better: setter, constructor, or field injection? Think why.

2021-02-09 07:50 UTC, Sofasmile commented on src/main/java/com/spring/service/impl/UserServiceImpl.java
> +    private UserDao userDao;
same here

2021-02-09 13:06 UTC, Sofasmile approved these changes

2021-02-09 16:05 UTC, merged