added file db.properties
Ilya-brinchuk/spring-project pull request #2
Opened 2021-02-09 18:39 UTC by Ilya-brinchuk

2021-02-09 18:45 UTC, RuslanIbIsh requested changes

2021-02-09 18:45 UTC, RuslanIbIsh commented on src/main/resources/db.properties
> +spring.jpa.show_sql=true
желательно разделить проперти на конфиг дб и хибера

2021-02-09 18:53 UTC, RuslanIbIsh approved these changes

2021-02-10 08:16 UTC, dmytro-hryhoruk approved these changes

2021-02-10 14:27 UTC, merged