added UserController, UserMapper, UserResponseDto MyWebInitializer, W…
Ilya-brinchuk/spring-project pull request #3
Opened 2021-02-10 18:59 UTC by Ilya-brinchuk

…ebConfig

2021-02-10 19:13 UTC, engineer027 approved these changes

2021-02-11 08:51 UTC, Sofasmile requested changes

2021-02-11 08:51 UTC, Sofasmile commented on src/main/java/com/spring/dao/impl/UserDaoImpl.java
> +    public User get(Long id) {
```suggestion
    public Optional<User> get(Long id) {
```

2021-02-11 10:26 UTC, Sofasmile approved these changes

2021-02-11 12:38 UTC, merged